default_platform(:ios)

lane :create_app do
	create_app_online #produce
end

platform :ios do
	before_all do
		Dotenv.load ".env"
	end
	
	desc "Signing"
	lane :signing do
		sync_code_signing #match
		mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
		update_code_signing_settings(profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']])
	end


  desc "Build app"
  lane :build do
      setupCodeSigning('28051993', '28051993', '/Users/Stephan/Desktop/ios_development.mobileprovision', '/Users/Stephan/Desktop/ios_development.cer')

      

      build_app(scheme: "Pipeline")

  end
end


def setupCodeSigning(keychainPassword, certificatePassword, profilePath, certificatePath)
  create_keychain(
    name: "CI",
    password: keychainPassword,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
  install_provisioning_profile(path: profilePath)
  import_certificate(
    certificate_path: certificatePath,
    certificate_password: certificatePassword,
    keychain_name: "CI",
    keychain_password: keychainPassword
  )
end
